### ISSUE TITLE
AttributeError: 'socket' object has no attribute 'client_socket_send_message'

### ISSUE THREAD

**Issue by tensorsofthewall** [minerllabs/minerl#580]
I just got started with minerl and wanted to visualize the agent, following the instructions on [https://minerl.readthedocs.io/en/latest/tutorials/minerl_tools.html#visualizing-the-data-minerl-viewer](url). However, when i try to run minerl.interactor I get the following error:

(mineRLEnv) [san2597@DLSys2021 ~]$ python -m minerl.interactor 6666
/home/san2597/anaconda3/envs/mineRLEnv/lib/python3.7/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
Malmo[None:7c3b10, proc=EXISTING, addr=localhost:31415, locked=True]
Traceback (most recent call last):
  File "/home/san2597/anaconda3/envs/mineRLEnv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/san2597/anaconda3/envs/mineRLEnv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/san2597/anaconda3/envs/mineRLEnv/lib/python3.7/site-packages/minerl/interactor/__main__.py", line 80, in <module>
    run_interactor(ip=opts.ip, port=opts.port)
  File "/home/san2597/anaconda3/envs/mineRLEnv/lib/python3.7/site-packages/minerl/interactor/__main__.py", line 57, in run_interactor
    instance, '{}:{}'.format(ip, port)
  File "/home/san2597/anaconda3/envs/mineRLEnv/lib/python3.7/site-packages/minerl/interactor/__main__.py", line 23, in request_interactor
    _MultiAgentEnv._TO_MOVE_hello(sock)
  File "/home/san2597/anaconda3/envs/mineRLEnv/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 792, in _TO_MOVE_hello
    instance.client_socket_send_message(("<MalmoEnv" + malmo_version + "/>").encode())
AttributeError: 'socket' object has no attribute 'client_socket_send_message'

I'm using the latest version of minerl in Anaconda. I tried changing python versions, but that didn't fix the issue.

Edit: Never mind, the interactor does not work with minerl version 0.4, downgraded to 0.3.7
