### ISSUE TITLE
Cannot download training dataset

### ISSUE THREAD

**Issue by ElleLeonne** [minerllabs/minerl#649]
I was able to download the repo just fine, but when I attempt to follow the instructions for downloading the dataset that are listed on the minerl website, I get:

import minerl
minerl.data.download('media/elle/Storage/Datasets/Games')

>AttributeError: partially initialized module 'minerl' has no attribute 'data' (most likely due to a circular import)

**Comment by Miffyli** [comment]
Hey. The data downloader only works in versions older then v1.0. See [this repo](https://github.com/minerllabs/basalt-2022-behavioural-cloning-baseline) for an example on how to download and use data with v1.0.

**Comment by gchhablani** [comment]
@Miffyli How do I download data for the latest version here?

**Comment by Miffyli** [comment]
@gchhablani If you are referring to the "original" MineRL dataset used in the earlier competitions, you can install it by installing `pip install minerl==0.4.4` and then checking the instructions in [this](https://minerl.readthedocs.io/en/v0.4.4/tutorials/data_sampling.html) doc.
